### ISSUE TITLE
Jira sensor is not working

### ISSUE THREAD

**Issue by sahilsk** [StackStorm-Exchange/stackstorm-jira#23]
I'm running stackstorm locally . Though simple actions like commenting on jira ticket  works but sensor isn't.
I did copy the private key into the stackstorm server. File does exist. 

But st2sensorcontainer is throwing this error; 

```
2019-02-01 12:59:06,409 139791374973040 INFO sensor_wrapper [-] Found config for sensor "JIRASensorForAPIv2"
2019-02-01 12:59:06,410 139791374973040 INFO sensor_wrapper [-] Watcher started
2019-02-01 12:59:06,410 139791374973040 INFO sensor_wrapper [-] Running sensor initialization code
2019-02-01 12:59:06,410 139791374973040 ERROR (unknown file) [-] Traceback (most recent call last):

2019-02-01 12:59:06,410 139791374973040 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 355, in <module>

2019-02-01 12:59:06,411 139791374973040 ERROR (unknown file) [-]
2019-02-01 12:59:06,411 139791374973040 ERROR (unknown file) [-] obj.run()

2019-02-01 12:59:06,412 139791374973040 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 212, in run

2019-02-01 12:59:06,413 139791374973040 ERROR (unknown file) [-]
2019-02-01 12:59:06,413 139791374973040 ERROR (unknown file) [-] self._sensor_instance.setup()

2019-02-01 12:59:06,414 139791374973040 ERROR (unknown file) [-]   File "/opt/stackstorm/packs/jira/sensors/jira_sensor_for_apiv2.py", line 47, in setup

2019-02-01 12:59:06,414 139791374973040 ERROR (unknown file) [-]
2019-02-01 12:59:06,414 139791374973040 ERROR (unknown file) [-] raise Exception('Cert file for JIRA OAuth not found at %s.' % rsa_cert_file)

2019-02-01 12:59:06,414 139791374973040 ERROR (unknown file) [-] Exception
2019-02-01 12:59:06,414 139791374973040 ERROR (unknown file) [-] :
2019-02-01 12:59:06,415 139791374973040 ERROR (unknown file) [-] Cert file for JIRA OAuth not found at /root/jira.pem.
2019-02-01 12:59:06,415 139791374973040 ERROR (unknown file) [-]

2019-02-01 12:59:06,415 139791374973040 INFO sensor_wrapper [-] Stopping trigger watcher
2019-02-01 12:59:06,417 139791374973040 INFO sensor_wrapper [-] Invoking cleanup on sensor
2019-02-01 12:59:06,483 140491509250160 INFO sensor_wrapper [-] Found config for sensor "JIRASensor"
2019-02-01 12:59:06,484 140491509250160 INFO sensor_wrapper [-] Watcher started
2019-02-01 12:59:06,484 140491509250160 INFO sensor_wrapper [-] Running sensor initialization code
2019-02-01 12:59:06,484 140491509250160 ERROR (unknown file) [-] Traceback (most recent call last):

2019-02-01 12:59:06,485 140491509250160 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 355, in <module>

2019-02-01 12:59:06,485 140491509250160 ERROR (unknown file) [-]
2019-02-01 12:59:06,485 140491509250160 ERROR (unknown file) [-] obj.run()

2019-02-01 12:59:06,485 140491509250160 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 212, in run

2019-02-01 12:59:06,486 140491509250160 ERROR (unknown file) [-]
2019-02-01 12:59:06,486 140491509250160 ERROR (unknown file) [-] self._sensor_instance.setup()

2019-02-01 12:59:06,486 140491509250160 ERROR (unknown file) [-]   File "/opt/stackstorm/packs/jira/sensors/jira_sensor.py", line 47, in setup

2019-02-01 12:59:06,487 140491509250160 ERROR (unknown file) [-]
2019-02-01 12:59:06,487 140491509250160 ERROR (unknown file) [-] raise Exception('Cert file for JIRA OAuth not found at %s.' % rsa_cert_file)

2019-02-01 12:59:06,487 140491509250160 ERROR (unknown file) [-] Exception
2019-02-01 12:59:06,487 140491509250160 ERROR (unknown file) [-] :
2019-02-01 12:59:06,488 140491509250160 ERROR (unknown file) [-] Cert file for JIRA OAuth not found at /root/jira.pem.
2019-02-01 12:59:06,488 140491509250160 ERROR (unknown file) [-]

2019-02-01 12:59:06,488 140491509250160 INFO sensor_wrapper [-] Stopping trigger watcher
2019-02-01 12:59:06,489 140491509250160 INFO sensor_wrapper [-] Invoking cleanup on sensor
^C
(
```

**Comment by sahilsk** [comment]
That's weird. I can run the sensorcontainer if i run it manually:


```
/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --debug --sensor-ref=jira.JIRASensorForAPIv2
```

```
pB8bwAnQEE39S1xXBl3lTc", oauth_signature="0D9lvIHZlMgLhfOLWy%2B8blGTX4RUSZkgGZHiTZgnvxNKNIpLaVMKtJ%2Fa%2FLIIWxylOfnmLASTCVuxCDNls09Y6VyHMD%2BUKiTX7GoQ2mEX03nT%2FfY8eKfq%2FlSQ%2FahxikhZrUyPGEhs2NDH7AsaIMxZdJTYyOgvGowCEg%2F%2FUJn8jKRBl8L%2BH6f%2FfDo3A%2Ftj9wi01RJx4BgToBvlS35BWdrDCesdAV1GCDJxyxTe5w9xxVE8%2BQdtaaxPVYpfitML6qv6vxXHqM71uj7wh6lLOKxGu%2Bpl1Vscq497gTVUybyag1cjpfbzR%2BYUh%2FWDKgbnqXjckfnGCxRcNhtvMDwlL8UhZw%3D%3D"'}
2019-02-01 13:05:29,481 DEBUG [-] Updated body: None
2019-02-01 13:05:29,801 DEBUG [-] http://stackstorm.xxx.com:8080 "GET /rest/api/2/search?jql=project%3DSELFSRV&validateQuery=True&startAt=0&maxResults=50 HTTP/1.1" 200 None
2019-02-01 13:05:30,585 DEBUG [-] 1 active sensor(s)



2019-02-01 13:05:35,585 DEBUG [-] 1 active sensor(s)
```

**Comment by nmaludy** [comment]
Guessing it's a permissions issue with the JIRA cert that you've configured.

Looks like you placed the cert in `/root/jira.pem`. The sensor runs as the `st2` user and most likely doesn't have permissions to read that cert file.

You need to place the `jira.pem` file in a directory that the `st2` user had access to and give that user permissions to read the file.

**Comment by sahilsk** [comment]
@nmaludy   You are right.  
I did give the key right permission and ownership, but i forgot about the parent directory: "root" 
After, changing the directory, it worked.

I wonder if we could add a little extra message for faster debugging:

https://github.com/StackStorm-Exchange/stackstorm-jira/blob/30933393d3aa6e327415ea8e73aa574ca97522f4/sensors/jira_sensor_for_apiv2.py#L44-L49


```
                raise Exception('Cert file for JIRA OAuth(%s) either does not exist or doesn't have right permissions including parent directories ' % rsa_cert_file)
```

**Comment by LindsayHill** [comment]
Feel free to open a PR to change the error message
